version: 2
jobs:
  build:
    docker:
      - image: python:2.7
        environment:
          TERM: linux
          TERMINFO: /etc/terminfo
    working_directory: /home/ubuntu/temboard-agent
    steps:
      - checkout
      - restore_cache:
          keys:
            - temboard-agent-{{ .Branch }}
            - temboard-agent-master
      - run:
          command: |
            set -x
            pip install --upgrade flake8 docutils
            git diff --check $(git merge-base origin/master $CIRCLE_SHA1)..$CIRCLE_SHA1
            flake8 temboard-agent/
            python setup.py --long-description | rst2html.py --verbose --halt=warning > README.html
      - store_artifacts:
          path: README.html
          destination: build/README.html
      - save_cache:
          key: temboard-agent-{{ .Branch }}
          paths:
            - "~/.cache/pip/"
